### ISSUE TITLE
Getting more than 100 tracks via getPlaylist

### ISSUE THREAD

**Issue by TalonGrayson** [kaaes/spotify-web-api-android#105]
Hi there,

Apologies if this isn't the correct place to ask.

I'm trying to get all track from a playlist and the playlist has more than 100 tracks within. Using the code below, I am able to get the first 100 tracks, but despite my efforts I am unable to figure out how to get the next 100 (or increase the limit). Could you tell me how to get all tracks, even if there are, say, thousands?

	public void TracksFromSpotifyPlaylist(final String playlistID) {

		api.setAccessToken(mToken);
		SpotifyService spotify = api.getService();

		spotify.getPlaylist(mUserID, playlistID, new Callback<Playlist>() {

			@Override
			public void success(Playlist playlist, retrofit.client.Response response) {

				QueueManager.spotifyPlaylistTracks.clear();
			
				//Only gets the first 100:
				for (PlaylistTrack track : playlist.tracks.items) {
					MusicTrack newTrack = new MusicTrack(track);
					QueueManager.spotifyPlaylistTracks.add(newTrack);
				}
			}

			@Override
			public void failure(RetrofitError error) {
				Log.i("Error", error.toString());
			}
		});
	}

**Comment by JonesN7** [comment]
+1

**Comment by JonesN7** [comment]
@TalonGrayson 

If you use the 	

    getPlaylist(String trackIds, Map<String,Object> options, retrofit.Callback<Tracks> callback)

call instead, you can feed in options with a map. You can edit your code like this (probably)

    Map<String, Object> options = new Map<String, Object>();
    options.put(SpotifyService.OFFSET, 0)
    options.put(SpotifyService.LIMIT, 2000) 
    spotifyService.getPlaylist(userId, playlistId, options, new Callback<Playlist>() {
    .......


And get litterally (two) tousands of tracks. Probably a good idea to limit it to do several calls and not set the limit too high.

**Comment by TalonGrayson** [comment]
Hi there,

Just wanted to reply to say thank you for the info. I haven't had a chance to try this out yet as I have barely even been at my PC over the last couple of weeks.

I will report back once I have tried out and hopefully we can close this :)

**Comment by kaaes** [comment]
If you'd like to fetch all tracks in the playlist you should use `getPlaylistTracks` method that allows to
request specific subset of tracks using `offset` and `limit` parameters.
Unfortunately setting `limit` to 2000 won't work because max size of the page is 100 (defined in the [endpoint docs](https://developer.spotify.com/web-api/get-playlists-tracks/)).

The response of this call is a [paging object](https://developer.spotify.com/web-api/object-model/#paging-object) that has the `total` field that will tell you how many tracks the playlist has as well as `offset` and `limit` fields that will tell you where in the track set you are.

So for a playlists with 268 tracks a simplified example could look like this:
```java
Map<String, Object> options = new Map<String, Object>();
options.put(SpotifyService.LIMIT, 100);

// get tracks 0-99
options.put(SpotifyService.OFFSET, 0);
Pager<PlaylistTrack> response = spotifyService.getPlaylistTracks(userId, playlistId, options);

// get tracks 100-199
options.put(SpotifyService.OFFSET, 100);
Pager<PlaylistTrack> response = spotifyService.getPlaylistTracks(userId, playlistId, options);

// get tracks 200-268
options.put(SpotifyService.OFFSET, 200);
Pager<PlaylistTrack> response = spotifyService.getPlaylistTracks(userId, playlistId, options);
```
Where you can keep querying as long as `offset` + `limit` < `total`
