### ISSUE TITLE
jitpack.io doesn't have the latest version?

### ISSUE THREAD

**Issue by gordonyoon** [kaaes/spotify-web-api-android#112]
I followed the instructions to integrate the api into my project.

For the most part, it works but it seems when I get it from jitpack.io, it may be an older version as I am unable to use some of the methods that should be available (e.g., me/playlists, which looks like a more recent commit).

**Comment by JohnnyCrazy** [comment]
Support for the `/me` Endpoint was added after the latest 0.2.0 release. ([Commits since 0.2.0](https://github.com/kaaes/spotify-web-api-android/compare/0.2.0...master))

AFAIK you either have to wait for @kaaes to deploy a new release or use the [SNAPSHOT-version](https://jitpack.io/#kaaes/spotify-web-api-android/-SNAPSHOT). (Instead of the `SNAPSHOT`-version you can also specify the hash of the commit)

**Comment by drinkthestars** [comment]
I believe the latest version is up on jitpack.io now
