### ISSUE TITLE
SearchTracks() TracksPager returning wrong value?

### ISSUE THREAD

**Issue by neatorobito** [kaaes/spotify-web-api-android#21]
I'm having some trouble searching for tracks. Maybe I'm doing something wrong as no one else seems to have reported the problem. Firstly, the `TracksPager` object returns [items](http://cl.ly/ZRgJ) as a list of `Tracks`. After reading through the code in the repo, I discovered that a `Tracks` object is a list of `Track` objects. I thought that this was a little weird. Further, if I call the [toString method on items](http://cl.ly/ZRz3), as in `tracksPager.tracks.items.toString();` Logcat prints out a list of objects, at their memory locations. However, if I call `tracksPager.tracks.items.get(0).tracks.get(0)`, I get a [null pointer exception.](http://cl.ly/ZRSK) Thanks for the help.

**Comment by thelinmichael** [comment]
Hey @markrjr! For the first point regarding the <code>TracksPager</code>, I understand that it looks a bit funny. This is because the search results from the Web API can return tracks, playlists, albums, and artists, all at the same time. Since this language binding only searches tracks, you'll only have a <code>tracks</code> property in the response.

For example: https://api.spotify.com/v1/search?query=Metallica&type=album,artist,playlist,track&limit=1
```
{
  "albums" : {
     "items": [],
     ...
   },
  "artists" : {
     "items": [],
     ...
   },
  "tracks" : {
     "items": [],
     ...
   },
 "playlists" : {
     "items": [],
     ...
   }
}
```

Regarding running the <code>toString</code> method on a List containing Track objects, I can agree that it'd be a nice to have if it'd output the Spotify Track URIs.

Lastly, either the items collection is empty, or it's failing because you're referring to a <code>tracks</code> object that doesn't exist. (<code>tracksPager.tracks.items.get(0)</code> is a Track object, which in turn doesn't have a <code>tracks</code> member.)
